// Code generated by go generate; DO NOT EDIT.

package leftturnassist_v0_1_0

const SigningHash = "f68d62a01b2300308384f7d7049b9a75f39c0ca4fc921d9f5728453d4ec93d8648355aa5feee8a25dea1ec0d93877c8c5769ffda2304c2595f73cdfbc9d743a5"
