// Code generated by go generate; DO NOT EDIT.

package leftturnassist_v0_1_0

const SigningHash = "b3dd3763dcf143e03cb9069360376842f523b43a2425999e3925ea6083675e0317d7bdfe7150a9d74629d01e7bf20edd751a65345292c2c4b664372b6396dd71"
