// Code generated by go generate; DO NOT EDIT.

package leftturnassist_v0_1_0

const SigningHash = "2094a99fc5c3d56f0ceca8fb112fc89fec15519c614423d9de639426e151cc9e20e56768d19173ee3a92126b6a51d354d5315cd80eb6c90251dbfd263d6e9f97"
