/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/sessions/': RouteRecordInfo<'/sessions/', '/sessions', Record<never, never>, Record<never, never>>,
    '/tmis/': RouteRecordInfo<'/tmis/', '/tmis', Record<never, never>, Record<never, never>>,
    '/tmis/[client]/[sessionID]/[template]/[id]/': RouteRecordInfo<'/tmis/[client]/[sessionID]/[template]/[id]/', '/tmis/:client/:sessionID/:template/:id', { client: ParamValue<true>, sessionID: ParamValue<true>, template: ParamValue<true>, id: ParamValue<true> }, { client: ParamValue<false>, sessionID: ParamValue<false>, template: ParamValue<false>, id: ParamValue<false> }>,
    '/tmis/[client]/[sessionID]/[template]/[id]/[version]/': RouteRecordInfo<'/tmis/[client]/[sessionID]/[template]/[id]/[version]/', '/tmis/:client/:sessionID/:template/:id/:version', { client: ParamValue<true>, sessionID: ParamValue<true>, template: ParamValue<true>, id: ParamValue<true>, version: ParamValue<true> }, { client: ParamValue<false>, sessionID: ParamValue<false>, template: ParamValue<false>, id: ParamValue<false>, version: ParamValue<false> }>,
  }
}
