/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/sessions/': RouteRecordInfo<
      '/sessions/',
      '/sessions',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tmis/': RouteRecordInfo<
      '/tmis/',
      '/tmis',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tmis/[client]/[sessionID]/[template]/[id]/': RouteRecordInfo<
      '/tmis/[client]/[sessionID]/[template]/[id]/',
      '/tmis/:client/:sessionID/:template/:id',
      { client: ParamValue<true>, id: ParamValue<true>, sessionID: ParamValue<true>, template: ParamValue<true> },
      { client: ParamValue<false>, id: ParamValue<false>, sessionID: ParamValue<false>, template: ParamValue<false> },
      | never
    >,
    '/tmis/[client]/[sessionID]/[template]/[id]/[version]/': RouteRecordInfo<
      '/tmis/[client]/[sessionID]/[template]/[id]/[version]/',
      '/tmis/:client/:sessionID/:template/:id/:version',
      { client: ParamValue<true>, id: ParamValue<true>, sessionID: ParamValue<true>, template: ParamValue<true>, version: ParamValue<true> },
      { client: ParamValue<false>, id: ParamValue<false>, sessionID: ParamValue<false>, template: ParamValue<false>, version: ParamValue<false> },
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/sessions/index.vue': {
      routes:
        | '/sessions/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/tmis/index.vue': {
      routes:
        | '/tmis/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/tmis/[client]/[sessionID]/[template]/[id]/index.vue': {
      routes:
        | '/tmis/[client]/[sessionID]/[template]/[id]/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/tmis/[client]/[sessionID]/[template]/[id]/[version]/index.vue': {
      routes:
        | '/tmis/[client]/[sessionID]/[template]/[id]/[version]/'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
