// Code generated by go generate; DO NOT EDIT.

package trustmodel_vcm_v0_0_1

const SigningHash = "15eab4d26df09f99e9dc74cbf8cc46d4819503bafb492c92f4d851f30eea3305c20b438af67485a96a535be45a1e61e0972e04debf8cc02d246e5d754d7d8f86"
