// Code generated by go generate; DO NOT EDIT.

package trustmodel_vcm_v0_0_1

const SigningHash = "f10114cedb1d8cff4faa21b31937eb76eb0452b81d790c9744527a32d8da388836709769be8d481be9607bf03449ef5cf117daa9e021f9452e652d063e0fef00"
