// Code generated by go generate; DO NOT EDIT.

package brussels_0_0_1

const SigningHash = "7f6195cb42390df43b9725c0e88ae056db119871d7789ba4bf8c9fee5d0f9d69b026522dff6b9a830210f5cea1cd4995cb8f647d3790c3574435cb26df25fd96"
