// Code generated by go generate; DO NOT EDIT.

package brussels_0_0_1

const SigningHash = "ac7c1f80ac344e66fa1937b6f55b6de9bc765a38d41a2b42b418d4cdb16d5d4c015e39803bd4b68882ac850fea09691d51d1ecb8e2abcc4b5b5d6d60b4aaa483"
