// Code generated by go generate; DO NOT EDIT.

package trustmodel_smtd_v0_0_1

const SigningHash = "71947afbabc81a0700aa7dd3f15484befda25d7c4bb1c62dde1357100f9b42f610222c8c60b40d00b22b5ea932d23f1a64c9a66f97c3aba68d73e54ad4db2f98"
