// Code generated by go generate; DO NOT EDIT.

package trustmodel_smtd_v0_0_1

const SigningHash = "86a0b90cc20b9507e304b8efdc45854558605b15d06d044dc0de9a1416a78598ea833f7f4992ac5f4a7a53ea42f4cdbde69b4e038cff306e7bc1714a74628c62"
