// Code generated by go generate; DO NOT EDIT.

package trustmodel_smtd_v0_0_1

const SigningHash = "22ec7c4bead2bf1a0279323ed8d6594ab9fcc2bb5cc6568d0e66b0a4900a9837228ebab61ffea6f0bd6ad00187d9ee3ec9a4ea858347120be2f03b09a17c1739"
