// Code generated by go generate; DO NOT EDIT.

package trustmodel_to_v0_0_1

const SigningHash = "d80fcaef2d3f0be514a66bfd0d7cd123e5c61e1429de4fb9ea7208d12a5e5b9d12d32c6be31baf2691c6ca1e5bc186fc92df2343facd1dfda571e4c79089e0e6"
