// Code generated by go generate; DO NOT EDIT.

package trustmodel_to_v0_0_1

const SigningHash = "295a4031c3af17018e92354c59ce1693d640d9b88580aa5c90999c97095d098d4ca333d47d5430a7dfb2bf8afc487013ec61b605bbac87a0019111618c068461"
