// Code generated by go generate; DO NOT EDIT.

package main

import _ "github.com/vs-uulm/go-taf/plugins/communication/filebased"
import _ "github.com/vs-uulm/go-taf/plugins/communication/kafkabased"
import _ "github.com/vs-uulm/go-taf/plugins/trustmodels/brussels"
import _ "github.com/vs-uulm/go-taf/plugins/trustmodels/brussels/v0_0_1"
import _ "github.com/vs-uulm/go-taf/plugins/trustmodels/examplemodel"
import _ "github.com/vs-uulm/go-taf/plugins/trustmodels/examplemodel/trustmodel-example-v0.0.1"
import _ "github.com/vs-uulm/go-taf/plugins/trustmodels/intersectionmovementassist"
import _ "github.com/vs-uulm/go-taf/plugins/trustmodels/intersectionmovementassist/trustmodel-ima-federated-v0.0.1"
import _ "github.com/vs-uulm/go-taf/plugins/trustmodels/intersectionmovementassist/trustmodel-ima-standalone-v0.0.1"
import _ "github.com/vs-uulm/go-taf/plugins/trustmodels/intersectionmovementassist/trustmodel-ima-standalone-v0.0.2"
import _ "github.com/vs-uulm/go-taf/plugins/trustmodels/intersectionmovementassist/trustmodel-ntm-standalone_v0.0.1"
import _ "github.com/vs-uulm/go-taf/plugins/trustmodels/leftturnassist"
import _ "github.com/vs-uulm/go-taf/plugins/trustmodels/leftturnassist/v0_1_0"
import _ "github.com/vs-uulm/go-taf/plugins/trustmodels/smtd"
import _ "github.com/vs-uulm/go-taf/plugins/trustmodels/smtd/trustmodel-smtd-v0.0.1"
import _ "github.com/vs-uulm/go-taf/plugins/trustmodels/taskoffloading"
import _ "github.com/vs-uulm/go-taf/plugins/trustmodels/taskoffloading/trustmodel-to-v0.0.1"
import _ "github.com/vs-uulm/go-taf/plugins/trustmodels/vehiclecomputermigration"
import _ "github.com/vs-uulm/go-taf/plugins/trustmodels/vehiclecomputermigration/trustmodel-vcm-v0.0.1"
