package message

type MessageSchema string

const (
	AIV_NOTIFY                    = "AIV_NOTIFY"
	AIV_REQUEST                   = "AIV_REQUEST"
	AIV_RESPONSE                  = "AIV_RESPONSE"
	AIV_SUBSCRIBE_REQUEST         = "AIV_SUBSCRIBE_REQUEST"
	AIV_SUBSCRIBE_RESPONSE        = "AIV_SUBSCRIBE_RESPONSE"
	AIV_UNSUBSCRIBE_REQUEST       = "AIV_UNSUBSCRIBE_REQUEST"
	AIV_UNSUBSCRIBE_RESPONSE      = "AIV_UNSUBSCRIBE_RESPONSE"
	GENERIC_ONE_WAY               = "GENERIC_ONE_WAY"
	GENERIC_REQUEST               = "GENERIC_REQUEST"
	GENERIC_RESPONSE              = "GENERIC_RESPONSE"
	GENERIC_SUBSCRIPTION_NOTIFY   = "GENERIC_SUBSCRIPTION_NOTIFY"
	GENERIC_SUBSCRIPTION_REQUEST  = "GENERIC_SUBSCRIPTION_REQUEST"
	GENERIC_SUBSCRIPTION_RESPONSE = "GENERIC_SUBSCRIPTION_RESPONSE"
	MBD_NOTIFY                    = "MBD_NOTIFY"
	MBD_SUBSCRIBE_REQUEST         = "MBD_SUBSCRIBE_REQUEST"
	MBD_SUBSCRIBE_RESPONSE        = "MBD_SUBSCRIBE_RESPONSE"
	MBD_UNSUBSCRIBE_REQUEST       = "MBD_UNSUBSCRIBE_REQUEST"
	MBD_UNSUBSCRIBE_RESPONSE      = "MBD_UNSUBSCRIBE_RESPONSE"
	TAQI_QUERY                    = "TAQI_QUERY"
	TAQI_RESULT                   = "TAQI_RESULT"
	TAS_TMT_DISCOVER              = "TAS_TMT_DISCOVER"
	TAS_TMT_OFFER                 = "TAS_TMT_OFFER"
	TAS_INIT_REQUEST              = "TAS_INIT_REQUEST"
	TAS_INIT_RESPONSE             = "TAS_INIT_RESPONSE"
	TAS_NOTIFY                    = "TAS_NOTIFY"
	TAS_SUBSCRIBE_REQUEST         = "TAS_SUBSCRIBE_REQUEST"
	TAS_SUBSCRIBE_RESPONSE        = "TAS_SUBSCRIBE_RESPONSE"
	TAS_TA_REQUEST                = "TAS_TA_REQUEST"
	TAS_TA_RESPONSE               = "TAS_TA_RESPONSE"
	TAS_TEARDOWN_REQUEST          = "TAS_TEARDOWN_REQUEST"
	TAS_TEARDOWN_RESPONSE         = "TAS_TEARDOWN_RESPONSE"
	TAS_UNSUBSCRIBE_REQUEST       = "TAS_UNSUBSCRIBE_REQUEST"
	TAS_UNSUBSCRIBE_RESPONSE      = "TAS_UNSUBSCRIBE_RESPONSE"
	TCH_INIT_REQUEST              = "TCH_INIT_REQUEST"
	TCH_INIT_RESPONSE             = "TCH_INIT_RESPONSE"
	TCH_NOTIFY                    = "TCH_NOTIFY"
	TCH_TC_REQUEST                = "TCH_TC_REQUEST"
	TCH_TC_RESPONSE               = "TCH_TC_RESPONSE"
	TEST_MESSAGE                  = "TEST_MESSAGE"
	V2X_CPM                       = "V2X_CPM"
	V2X_CAM                       = "V2X_CAM"
	V2X_NTM                       = "V2X_NTM"
)

var SchemaMap = map[string]MessageSchema{
	AIV_NOTIFY:                    AIV_NOTIFY,
	AIV_REQUEST:                   AIV_REQUEST,
	AIV_RESPONSE:                  AIV_RESPONSE,
	AIV_SUBSCRIBE_REQUEST:         AIV_SUBSCRIBE_REQUEST,
	AIV_SUBSCRIBE_RESPONSE:        AIV_SUBSCRIBE_RESPONSE,
	AIV_UNSUBSCRIBE_REQUEST:       AIV_UNSUBSCRIBE_REQUEST,
	AIV_UNSUBSCRIBE_RESPONSE:      AIV_UNSUBSCRIBE_RESPONSE,
	GENERIC_ONE_WAY:               GENERIC_ONE_WAY,
	GENERIC_REQUEST:               GENERIC_REQUEST,
	GENERIC_RESPONSE:              GENERIC_RESPONSE,
	GENERIC_SUBSCRIPTION_NOTIFY:   GENERIC_SUBSCRIPTION_NOTIFY,
	GENERIC_SUBSCRIPTION_REQUEST:  GENERIC_SUBSCRIPTION_REQUEST,
	GENERIC_SUBSCRIPTION_RESPONSE: GENERIC_SUBSCRIPTION_RESPONSE,
	MBD_NOTIFY:                    MBD_NOTIFY,
	MBD_SUBSCRIBE_REQUEST:         MBD_SUBSCRIBE_REQUEST,
	MBD_SUBSCRIBE_RESPONSE:        MBD_SUBSCRIBE_RESPONSE,
	MBD_UNSUBSCRIBE_REQUEST:       MBD_UNSUBSCRIBE_REQUEST,
	MBD_UNSUBSCRIBE_RESPONSE:      MBD_UNSUBSCRIBE_RESPONSE,
	TAQI_QUERY:                    TAQI_QUERY,
	TAQI_RESULT:                   TAQI_RESULT,
	TAS_TMT_DISCOVER:              TAS_TMT_DISCOVER,
	TAS_TMT_OFFER:                 TAS_TMT_OFFER,
	TAS_INIT_REQUEST:              TAS_INIT_REQUEST,
	TAS_INIT_RESPONSE:             TAS_INIT_RESPONSE,
	TAS_NOTIFY:                    TAS_NOTIFY,
	TAS_SUBSCRIBE_REQUEST:         TAS_SUBSCRIBE_REQUEST,
	TAS_SUBSCRIBE_RESPONSE:        TAS_SUBSCRIBE_RESPONSE,
	TAS_TA_REQUEST:                TAS_TA_REQUEST,
	TAS_TA_RESPONSE:               TAS_TA_RESPONSE,
	TAS_TEARDOWN_REQUEST:          TAS_TEARDOWN_REQUEST,
	TAS_TEARDOWN_RESPONSE:         TAS_TEARDOWN_RESPONSE,
	TAS_UNSUBSCRIBE_REQUEST:       TAS_UNSUBSCRIBE_REQUEST,
	TAS_UNSUBSCRIBE_RESPONSE:      TAS_UNSUBSCRIBE_RESPONSE,
	TCH_INIT_REQUEST:              TCH_INIT_REQUEST,
	TCH_INIT_RESPONSE:             TCH_INIT_RESPONSE,
	TCH_NOTIFY:                    TCH_NOTIFY,
	TCH_TC_REQUEST:                TCH_TC_REQUEST,
	TCH_TC_RESPONSE:               TCH_TC_RESPONSE,
	TEST_MESSAGE:                  TEST_MESSAGE,
	V2X_CPM:                       V2X_CPM,
	V2X_CAM:                       V2X_CAM,
	V2X_NTM:                       V2X_NTM,
}

var ServiceMap = map[MessageSchema]string{
	AIV_NOTIFY:                    "ECI",
	AIV_REQUEST:                   "ECI",
	AIV_RESPONSE:                  "ECI",
	AIV_SUBSCRIBE_REQUEST:         "ECI",
	AIV_SUBSCRIBE_RESPONSE:        "ECI",
	AIV_UNSUBSCRIBE_REQUEST:       "ECI",
	AIV_UNSUBSCRIBE_RESPONSE:      "ECI",
	GENERIC_ONE_WAY:               "INVALID",
	GENERIC_REQUEST:               "INVALID",
	GENERIC_RESPONSE:              "INVALID",
	GENERIC_SUBSCRIPTION_NOTIFY:   "INVALID",
	GENERIC_SUBSCRIPTION_REQUEST:  "INVALID",
	GENERIC_SUBSCRIPTION_RESPONSE: "INVALID",
	MBD_NOTIFY:                    "ECI",
	MBD_SUBSCRIBE_REQUEST:         "ECI",
	MBD_SUBSCRIBE_RESPONSE:        "ECI",
	MBD_UNSUBSCRIBE_REQUEST:       "ECI",
	MBD_UNSUBSCRIBE_RESPONSE:      "ECI",
	TAQI_QUERY:                    "TAQI",
	TAQI_RESULT:                   "TAQI",
	TAS_TMT_DISCOVER:              "TAS",
	TAS_TMT_OFFER:                 "TAS",
	TAS_INIT_REQUEST:              "TAS",
	TAS_INIT_RESPONSE:             "TAS",
	TAS_NOTIFY:                    "TAS",
	TAS_SUBSCRIBE_REQUEST:         "TAS",
	TAS_SUBSCRIBE_RESPONSE:        "TAS",
	TAS_TA_REQUEST:                "TAS",
	TAS_TA_RESPONSE:               "TAS",
	TAS_TEARDOWN_REQUEST:          "TAS",
	TAS_TEARDOWN_RESPONSE:         "TAS",
	TAS_UNSUBSCRIBE_REQUEST:       "TAS",
	TAS_UNSUBSCRIBE_RESPONSE:      "TAS",
	TCH_INIT_REQUEST:              "UNKNOWN",
	TCH_INIT_RESPONSE:             "UNKNOWN",
	TCH_NOTIFY:                    "ECI",
	TCH_TC_REQUEST:                "UNKNOWN",
	TCH_TC_RESPONSE:               "UNKNOWN",
	TEST_MESSAGE:                  "INVALID",
	V2X_CPM:                       "V2X",
	V2X_CAM:                       "V2X",
	V2X_NTM:                       "V2X",
}
