// Code generated by go generate; DO NOT EDIT.

package trustmodel_example_v0_0_1

const SigningHash = "cb4064c455300ba9179206fb9b0ab41ee95ba89dddea60ea456d96427ef6935beca6616ae69428a6697171cd079029744cfce642dfcd08aac7447b3c45e5e4e5"
