// Code generated by go generate; DO NOT EDIT.

package trustmodel_example_v0_0_1

const SigningHash = "fde8420b8fcb24ef83b82d7871819b6181f065a3ad64e40a507bab3a98f995cc93002685a410c7ca2b9476bf258070a8371237f59390516becb92153e3d39c18"
